on:
  push:
    branches: [ "main" ]  # Se déclenche sur push vers "main"

jobs:
  lint-and-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint code
        run: npm run lint  # Si échec, le workflow s'arrête

      - name: Merge into prod
        if: success()  # Si le linting passe
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout prod
          git merge main
          git push origin prod
